config/routes.rb
Datasets::Application.routes.draw do
  resources :datasets

  

end

app/models/dataset.rb
class Dataset < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  before_action :set_dataset, only: [:show, :edit, :update, :destroy]

  # GET /datasets
  # GET /datasets.json
  def index
    @datasets = Dataset.all
  end

  # GET /datasets/1
  # GET /datasets/1.json
  def show
  end

  # GET /datasets/new
  def new
    @dataset = Dataset.new
  end

  # GET /datasets/1/edit
  def edit
  end

  # POST /datasets
  # POST /datasets.json
  def create
    @dataset = Dataset.new(dataset_params)

    respond_to do |format|
      if @dataset.save
        format.html { redirect_to @dataset, notice: 'Dataset was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dataset }
      else
        format.html { render action: 'new' }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datasets/1
  # PATCH/PUT /datasets/1.json
  def update
    respond_to do |format|
      if @dataset.update(dataset_params)
        format.html { redirect_to @dataset, notice: 'Dataset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datasets/1
  # DELETE /datasets/1.json
  def destroy
    @dataset.destroy
    respond_to do |format|
      format.html { redirect_to datasets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dataset
      @dataset = Dataset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dataset_params
      params.require(:dataset).permit(:name, :frequency, :system, :format, :url, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datasets_helper.rb
module DatasetsHelper
end

app/views/datasets/_form.html.erb
<%= form_for(@dataset) do |f| %>
  <% if @dataset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dataset.errors.count, "error") %> prohibited this dataset from being saved:</h2>

      <ul>
      <% @dataset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :frequency %><br>
    <%= f.text_field :frequency %>
  </div>
  <div class="field">
    <%= f.label :system %><br>
    <%= f.text_field :system %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/datasets/edit.html.erb
<h1>Editing dataset</h1>

<%= render 'form' %>

<%= link_to 'Show', @dataset %> |
<%= link_to 'Back', datasets_path %>

app/views/datasets/index.html.erb
<h1>Listing datasets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Frequency</th>
      <th>System</th>
      <th>Format</th>
      <th>Url</th>
      <th>Notes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @datasets.each do |dataset| %>
      <tr>
        <td><%= dataset.name %></td>
        <td><%= dataset.frequency %></td>
        <td><%= dataset.system %></td>
        <td><%= dataset.format %></td>
        <td><%= dataset.url %></td>
        <td><%= dataset.notes %></td>
        <td><%= link_to 'Show', dataset %></td>
        <td><%= link_to 'Edit', edit_dataset_path(dataset) %></td>
        <td><%= link_to 'Destroy', dataset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dataset', new_dataset_path %>

app/views/datasets/new.html.erb
<h1>New dataset</h1>

<%= render 'form' %>

<%= link_to 'Back', datasets_path %>

app/views/datasets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dataset.name %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @dataset.frequency %>
</p>

<p>
  <strong>System:</strong>
  <%= @dataset.system %>
</p>

<p>
  <strong>Format:</strong>
  <%= @dataset.format %>
</p>

<p>
  <strong>Url:</strong>
  <%= @dataset.url %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @dataset.notes %>
</p>

<%= link_to 'Edit', edit_dataset_path(@dataset) %> |
<%= link_to 'Back', datasets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Datasets</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>